"""empty message

Revision ID: 991ed8795e58
Revises: 6d7aabb9bcdf
Create Date: 2018-07-13 16:47:58.006983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991ed8795e58'
down_revision = '6d7aabb9bcdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('activity', 'name')
    op.drop_column('activity', 'reference')
    op.add_column('material', sa.Column('upload_date', sa.Date(), nullable=False))
    op.drop_column('material', 'name')
    op.drop_column('material', 'reference')
    op.add_column('student_work', sa.Column('comment', sa.String(length=300), nullable=True))
    op.add_column('student_work', sa.Column('evaluation_date', sa.Date(), nullable=True))
    op.add_column('student_work', sa.Column('mark', sa.Float(), nullable=True))
    op.add_column('student_work', sa.Column('student_id', sa.Integer(), nullable=False))
    op.add_column('student_work', sa.Column('upload_date', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'student_work', 'user', ['student_id'], ['id'])
    op.drop_column('student_work', 'id')
    op.drop_column('student_work', 'name')
    op.drop_column('student_work', 'reference')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_work', sa.Column('reference', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('student_work', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('student_work', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'student_work', type_='foreignkey')
    op.drop_column('student_work', 'upload_date')
    op.drop_column('student_work', 'student_id')
    op.drop_column('student_work', 'mark')
    op.drop_column('student_work', 'evaluation_date')
    op.drop_column('student_work', 'comment')
    op.add_column('material', sa.Column('reference', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('material', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('material', 'upload_date')
    op.add_column('activity', sa.Column('reference', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('activity', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_table('file')
    # ### end Alembic commands ###
