"""empty message

Revision ID: efc80107167c
Revises: 991ed8795e58
Create Date: 2018-07-13 17:19:58.139453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efc80107167c'
down_revision = '991ed8795e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('activity', sa.Column('reference', sa.String(), nullable=False))
    op.add_column('material', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('material', sa.Column('reference', sa.String(), nullable=False))
    op.add_column('student_work', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('student_work', sa.Column('reference', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_work', 'reference')
    op.drop_column('student_work', 'name')
    op.drop_column('material', 'reference')
    op.drop_column('material', 'name')
    op.drop_column('activity', 'reference')
    op.drop_column('activity', 'name')
    # ### end Alembic commands ###
